version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: vira_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ViraDb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  seq:
    image: datalust/seq:latest
    container_name: vira_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
volumes:
    pgdata:
        
